server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.129
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.56.129
ly:
  sms:
    accessKeyId: LTAIfasuMoCiRsR4 #自己的accessKeyId
    accessKeySecret: i90JWQiOBGHPVHpWPLQIpmrUdRVy5N #自己的accesskeysecret
    signName: 华科凉介 #签名名称
    verifyCodeTemplate: SMS_164506046 #模板名称