server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false #关闭缓存，可以热部署html，但是在IDEA中需要重新build一下html
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka